name: Run UID Logger

on:
  schedule:
    - cron: "*/1 * * * *"   # يشتغل كل دقيقة
  workflow_dispatch:        # تقدر تشغله يدوي من GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install requests
      - name: Run bot
        run: python bot.py